openapi: 3.1.0
x-stoplight:
  id: c1yu0u08jvja9
info:
  title: version2
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/notes/{noteId}':
    parameters:
      - schema:
          type: string
        name: noteId
        in: path
        required: true
    get:
      summary: get note
      tags:
        - notes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
      operationId: get-notes-id
      description: 指定した投稿を取得します。
    delete:
      summary: delete note
      tags: []
      responses: {}
      operationId: delete-notes-id
      description: 指定した投稿を削除します
  '/notes/{noteId}/replies':
    parameters:
      - schema:
          type: string
        name: noteId
        in: path
        required: true
    get:
      summary: get replies
      tags:
        - notes
      responses: {}
      operationId: get-notes-noteId-replies
      parameters:
        - schema:
            type: string
          in: query
          name: sinceId
          description: 指定すると、その投稿を基点としてより新しい投稿を取得します
        - schema:
            type: string
          in: query
          name: untilId
          description: 指定すると、その投稿を基点としてより古い投稿を取得します
        - schema:
            type: number
            minimum: 1
            maximum: 100
          in: query
          name: limit
          description: 取得する件数。デフォルトは10
      description: 指定した投稿への返信を取得します。
  '/notes/{noteId}/renotes':
    parameters:
      - schema:
          type: string
        name: noteId
        in: path
        required: true
    get:
      summary: get renotes
      tags:
        - notes
      responses: {}
      operationId: get-notes-noteId-renotes
      description: 指定した投稿のRenote一覧を取得します。
      parameters:
        - schema:
            type: number
            minimum: 1
            maximum: 100
          in: query
          name: limit
          description: 取得する件数。デフォルトは10
        - schema:
            type: string
          in: query
          name: sinceId
        - schema:
            type: string
          in: query
          name: "untilId\t"
  '/notes/{noteId}/reactions':
    parameters:
      - schema:
          type: string
        name: noteId
        in: path
        required: true
    post:
      summary: add reaction
      tags:
        - notes
      responses: {}
      operationId: post-notes-noteId-reactions
      description: 指定した投稿にリアクションします。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reaction:
                  type: string
                  description: リアクション
                dislike:
                  type: string
                  description: きらい
    delete:
      summary: remove reaction
      tags:
        - notes
      responses: {}
      operationId: delete-notes-noteId-reactions
      description: 指定した投稿へのリアクションを取り消します。
    get:
      summary: ''
      operationId: get-notes-noteId-reactions
      responses:
        '200':
          description: OK
      description: 指定した投稿のリアクション一覧を取得します。
      parameters:
        - schema:
            type: string
          in: query
          name: type
        - schema:
            type: number
            minimum: 1
            maximum: 100
          in: query
          name: limit
        - schema:
            type: number
          in: query
          name: offset
        - schema:
            type: string
          in: query
          name: sinceId
        - schema:
            type: string
          in: query
          name: untilId
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
    Note:
      title: Note
      x-stoplight:
        id: 5pb42iqlwc2ck
      type: object
      properties:
        id:
          type: string
          description: ノートのId
        createdAt:
          type: string
          description: ノートの作成日時
        text:
          type:
            - string
            - 'null'
          description: ノートの内容
        cw:
          type:
            - string
            - 'null'
          description: ノートに対する注意
        user:
          $ref: '#/components/schemas/NoteUser'
        userId:
          type: string
          description: ノート作者のId
        reply:
          $ref: '#/components/schemas/Note'
        replyId:
          type: string
        renote:
          $ref: '#/components/schemas/Note'
        renoteId:
          type: string
        files:
          type: array
          items:
            $ref: '#/components/schemas/DriveFile'
        fileIds:
          type: array
          items:
            type: string
        visibility:
          type: string
        myReaction:
          type: string
        reactions:
          type: array
          items:
            type: object
            properties:
              string:
                type: number
        poll:
          type: string
        emojis:
          type: string
    NoteUser:
      title: NoteUser
      x-stoplight:
        id: nannh5c1apotg
      type: object
      properties:
        id:
          type: string
        host:
          type:
            - string
            - 'null'
        name:
          type: string
        onlineStatus:
          type: string
        avatarUrl:
          type: string
        avatarBlurhash:
          type: string
        emojis:
          type: string
        instance:
          $ref: '#/components/schemas/LiteInstance'
    LiteInstance:
      title: LiteInstance
      x-stoplight:
        id: 938vhemi8kqeu
      type: object
      properties:
        host:
          type: string
        name:
          type: string
        softwareName:
          type: string
        softwareversion:
          type: string
        iconUrl:
          type: string
        faviconUrl:
          type: string
        themeColor:
          type: string
    DriveFile:
      title: DriveFile
      x-stoplight:
        id: urs7nk38s41f8
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        isSensitive:
          type: string
        name:
          type: string
        thumbnailUrl:
          type: string
        url:
          type: string
        type:
          type: string
        size:
          type: string
        md5:
          type: string
        blurhash:
          type: string
        properties:
          type: string
